#!/usr/bin/env perl
use strict;
use warnings;
use utf8;
use FindBin;
use File::Path qw(make_path);
use JSON::PP;
use open qw(:std :encoding(UTF-8));

my $root = "$FindBin::Bin/..";
my $json = JSON::PP->new->canonical;

sub read_json {
    my ($path) = @_;
    open my $fh, '<:encoding(UTF-8)', $path or die "Cannot read $path: $!\n";
    local $/;
    return $json->decode(<$fh>);
}

sub write_text {
    my ($path, $content) = @_;
    open my $fh, '>:encoding(UTF-8)', $path or die "Cannot write $path: $!\n";
    print {$fh} $content;
    close $fh or die "Cannot close $path: $!\n";
}

sub yaml_string { return $json->encode($_[0] // '') }

my $claims = read_json("$root/data/claims.json");
my %claims_by_id = map { $_->{id} => $_ } @{$claims->{entries}};
my $publication = read_json("$root/data/publication.json");
my %publication_by_id = map { $_->{claim_id} => $_ } @{$publication->{entries}};
my @record_paths = sort glob "$root/editorial/records/*.json";
make_path("$root/docs/_claims", "$root/social/carousels");

for my $record_path (@record_paths) {
    my $record = read_json($record_path);
    my $id = $record->{claim_id};
    my $claim = $claims_by_id{$id} or die "No canonical claim for $id\n";
    my $copy = $record->{publication_copy};
    next unless length($copy->{title} // '');

    my $website = $copy->{website};
    my $number = 0 + ($id =~ /([0-9]+)$/)[0];
    my $publication_state = $publication_by_id{$id}{state} // 'withheld';
    my $published = $publication_state eq 'published' ? 'true' : 'false';
    my $ot_text = join ' ', map { $_->{text} } @{$claim->{ot_text}{verses}};
    my $ot_note = join ' ', map { @{$_->{notes}} } @{$claim->{ot_text}{verses}};
    my @frontmatter = (
        '---',
        '# Generated by scripts/generate_publication_copy.pl; edit the editorial record.',
        "published: $published",
        'title: ' . yaml_string($copy->{title}),
        'description: ' . yaml_string($website->{description}),
        'robots: ' . yaml_string($published eq 'true' ? 'index, follow' : 'noindex, nofollow'),
        "claim_number: $number",
        'editorial_status: ' . yaml_string($record->{status}),
        'publication_state: ' . yaml_string($publication_state),
        'summary: ' . yaml_string($website->{summary}),
        'ot_reference: ' . yaml_string($claim->{ot_passage}{source}),
        'ot_text: ' . yaml_string($ot_text),
        'ot_note: ' . yaml_string($ot_note),
        'christian_case: ' . yaml_string($website->{christian_case}),
        'critical_case: ' . yaml_string($website->{critical_case}),
        'verdict_label: ' . yaml_string($website->{verdict_label}),
        'verdict: ' . yaml_string($website->{verdict}),
        '---', '',
    );

    my @source_lines;
    for my $source (@{$record->{sources}}) {
        next unless $source->{checked};
        my $label = $source->{title};
        $label = "[$label]($source->{url})" if $source->{url};
        my $author = length($source->{author}) ? "$source->{author}, " : '';
        push @source_lines, "- $author$label. $source->{publisher}; $source->{locator}.";
    }
    push @source_lines, '', 'Biblical quotations are from the Berean Standard Bible (BSB), public domain.', '';
    write_text("$root/docs/_claims/$id.md", join("\n", @frontmatter, @source_lines));

    write_text("$root/social/carousels/$id.json", JSON::PP->new->canonical->pretty->encode({
        schema_version => 1,
        claim_id => $id,
        editorial_status => $record->{status},
        title => $copy->{title},
        source_url => "https://nonprophet.app/claims/$id/",
        slides => $copy->{carousel},
    }));
}

print "Generated publication copy for " . scalar(@record_paths) . " editorial records\n";
